# Generated by Django 5.1.4 on 2024-12-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='selected_question_ids',
            field=models.JSONField(default=list),
        ),
    ]
